name: Checks

on:
  push:
  pull_request:

# thanks red or wherever you got it from
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.8"
        tox_env:
          - style-black
          - style-ruff
        include:
          - tox_env: style-black
            friendly_name: Style (black)
          - tox_env: style-ruff
            friendly_name: Style (ruff)

      fail-fast: false

    name: Tox - ${{ matrix.python_version }} - ${{ matrix.friendly_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      # caching cuts down time for tox (for example black) from ~40 secs to 4
      - name: Cache tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ matrix.python_version }}-${{ matrix.tox_env }}-${{ hashFiles('tox.ini') }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox: ${{ matrix.friendly_name }}"
        env:
          TOXENV: ${{ matrix.tox_env }}
        run: |
          tox
