name: Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ruff & Black Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.12.0 ruff==0.12.5

      - name: Run Ruff
        run: ruff check .

      - name: Run Black (check only)
        run: black . --check --diff
